### ISSUE TITLE
Oberpfaffenhofen human tracking

### ISSUE THREAD

**Issue by airballking** [code-iai/saphari_final_review#11]
- [ ] play back bags which Rico sent
- [ ] get corresponding frames of kinects into urdf
- [ ] try playback together with simulation for software tests
